/*
 * This source file was generated by the Gradle 'init' task
 */
package taller4;


import java.util.Random;

public class App {

    public static void main(String[] args) {
        try {
            System.out.println(imparHastaN(200));
            System.out.println(fibonacci(10));
            int cantidad = new Random().nextInt(11) + 20;
            for (int i = 0; i < cantidad; i++) {
                System.out.println(raizCuadradaAleatoria());
            }
            System.out.println(contarParesAleatorios(10, 50));
            System.out.println(sumarAleatorios(10));
            System.out.println(sorteoLoteria());
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
    }

    public static String imparHastaN(int n) throws Exception {
        if (n < 100 || n > 500) {
            throw new Exception("El número debe estar entre 100 y 500");
        }
        StringBuilder sb = new StringBuilder();
        for (int i = 1; i <= n; i++) {
            if (i % 2 != 0) {
                sb.append(i).append(",");
                if ((i - 1) % 8 == 0 && i != 1) {
                    sb.append("\n");
                }
            }
        }
        return sb.toString();
    }

    public static String fibonacci(int n) throws Exception {
        if (n < 2) {
            throw new Exception("N debe ser mayor que 2");
        }
        StringBuilder sb = new StringBuilder();
        int a = 0, b = 1;
        for (int i = 0; i < n; i++) {
            sb.append(a).append(",");
            int temp = a;
            a = b;
            b = temp + b;
        }
        return sb.toString();
    }

    public static double raizCuadradaAleatoria() {
        Random random = new Random();
        int numero = random.nextInt(354) + 2;
        return Math.sqrt(numero);
    }

    public static String contarParesAleatorios(int inicio, int fin) throws Exception {
        if (inicio >= fin) {
            throw new Exception("El número inicial debe ser menor que el número final");
        }
        int count = 0;
        Random random = new Random();
        for (int i = 0; i < 900; i++) {
            int numero = random.nextInt(fin - inicio + 1) + inicio;
            if (numero % 2 == 0) {
                count++;
            }
        }
        return "Se generaron " + count + " números pares";
    }

    public static double sumarAleatorios(int cantidad) {
        double suma = 0;
        Random random = new Random();
        for (int i = 0; i < cantidad; i++) {
            suma += random.nextInt(100);
        }
        return suma;
    }

    public static String sorteoLoteria() {
        StringBuilder sb = new StringBuilder();
        Random random = new Random();
        for (int i = 20; i > 0; i--) {
            int numero = random.nextInt(9000) + 1000;
            int serie = random.nextInt(50) + 100;
            sb.append("Sorteo # ").append(i).append(" - Número Premiado ").append(numero).append(" - Serie ").append(serie).append("\n");
            if (i == 6) {
                sb.append("=======PREMIOS MENORES=======\n");
            } else if (i == 2) {
                sb.append("=======PREMIOS SECOS=========\n");
            } else if (i == 1) {
                sb.append("=======Premio mayor==========\n");
            }
        }
        return sb.toString();
    }
}
